:jbake-type: page
:jbake-status: published

= Installation
Use the following command to install Nokee on your system:

IMPORTANT: Please inspect https://raw.githubusercontent.com/nokeedev/install.nokee.dev/main/install.sh and/or https://raw.githubusercontent.com/nokeedev/install.nokee.dev/main/install.ps1 before running any of these scripts to ensure safety.
We already know it's safe, but you should verify the security and contents of *any* script from the internet you are not familiar with.
All of these scripts download a remote shell script and execute it on your machine.
We take security very seriously.

[[curl]]
==== via curl

.Install using curl
[source,sh]
----
bash <(curl -fsSL https://nokee.dev/install.sh)
----

[[wget]]
==== via wget

.Install using wget
[source,sh]
----
bash <(wget https://nokee.dev/install.sh -O -)
----

[[powershell]]
==== via powershell

.Install using powershell
[source,powershell]
----
Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-Expression (Invoke-Webrequest 'https://nokee.dev/install.ps1' -UseBasicParsing).Content
----

[[manually]]
==== by hand

The just of the install script above is to install the nokee.init.gradle script inside your Gradle's init.d directory of your current user.
The script performs additional checks to a successful start with Nokee.
To manually install Nokee's conveniences on your system, you have to...

1. Download the nokee.init.gradle script available.
2. Copy the script to the `~/.gradle/init.d` directory. Note that you may need to create this directory before copying the script.
3. Profit!

IMPORTANT: Please ensure you have a working link:https://gradle.org/install[installation of Gradle].
